AWSTemplateFormatVersion: '2010-09-09'
Description: Redis for Lambda observability
Transform: AWS::Serverless-2016-10-31
Parameters:
  pDescription:
    Type: String
    Default: observability-redis
  pVpcId:
    Type: String
  pSubnetIds:
    Type: List<String>
  pIngressSG:
    Type: String
Resources:
  RedisSubnets:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      Description: !Ref pDescription
      SubnetIds: !Ref pSubnetIds
  RedisSGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref pDescription
      VpcId: !Ref pVpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 6379
        ToPort: 6379
        SourceSecurityGroupId: !Ref pIngressSG
  Redis:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: cache.t3.small
      CacheSubnetGroupName: !Ref RedisSubnets
      Engine: redis
      NumCacheNodes: 1
      VpcSecurityGroupIds:
      - !Ref RedisSGroup
Outputs:
  outRedisSubnets:
    Value: !Ref RedisSubnets
  outRedisSGroup:
    Value: !Ref RedisSGroup
  outRedis:
    Value: !Ref Redis